monolog:
    channels: ['app']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/prod.log"
            level: error
            channels: ["!event", "!doctrine"]
        console:
            type: console
            channels: ["!event", "!doctrine"]
